server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/saas_mvp?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

  config:
    import: optional:nacos:saas-dev.yml

  cloud:
    nacos:
      server-addr: localhost:8848
      config:
        namespace: fc4a65ae-c645-4b25-a220-02b2c1ec8a49
        file-extension: yml