spring:
  application:
    name: saas-mvp

  profiles:
    active: dev

  security:
    user:
      name: user
      password: user123

  sql:
    init:
      mode: always

mybatis-plus:
  type-handlers-package: com.lsxuan.saas.infrastructure.persistence.typehandler